name: Download PR Files to EC2

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-18-185-57-130.eu-central-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Get PR changed files
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files > pr_files.json

      - name: Add repo name and commit id to the JSON
        run: |
          COMMIT_ID="${{ github.event.pull_request.head.sha }}"
          REPO_NAME="${{ github.repository }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"

          # create a new JSON file that includes repo name, commit ID, and the PR files
          jq -n \
            --arg repo_name "$REPO_NAME" \
            --arg commit_id "$COMMIT_ID" \
            --arg pr_number "$PR_NUMBER" \
            --slurpfile pr_files pr_files.json \
            '{repo_name: $repo_name, commit_id: $commit_id, pr_number: $pr_number, pr_files: $pr_files}' > pr_data.json

      - name: Copy PR files to EC2
        run: |
          scp -i ~/.ssh/id_rsa pr_data.json ec2-user@ec2-18-185-57-130.eu-central-1.compute.amazonaws.com:/home/ec2-user/xiao/pr_data_${{ github.event.pull_request.number }}.json

      - name: Log into EC2, activate virtual environment and run code reviewer
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-18-185-57-130.eu-central-1.compute.amazonaws.com << 'EOF'
            source /home/ec2-user/xiao/venv/bin/activate
            python /home/ec2-user/xiao/code_reviewer.py /home/ec2-user/xiao/pr_data_${{ github.event.pull_request.number }}.json
          EOF
